spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://korea-it.cng2osy0onis.ap-northeast-2.rds.amazonaws.com:3306/toyproject
    username: admin
    password: 1q2w3e4r!!
